name: Build APK Artifact

on:
  push:
    branches: develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build APK artifact workflow started"
      - uses: actions/checkout@v3

      - name: Setup Flutter & build APK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.1'
          channel: 'stable'
      - run: flutter --version
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build apk --release

      - name: Upload apk build as an Artifact
        uses: actions/upload-artifact@v1
        with:
          name: staging-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk